export { default as Footer } from "./Footer"
export { default as Hero } from "./Hero"
export { default as Project } from "./Project"
export { default as Reveal } from "./Reveal"
export { default as Sidebar } from "./Sidebar"
export { default as SkillSlider } from "./SkillSlider"
export { default as Timeline } from "./Timeline"
